### ISSUE TITLE
Unable to declare custom CSS variables

### ISSUE THREAD

**Issue by Glamurio** [jaraco/cssutils#14]
Normally, CSS can set custom variables via the :root element selector, as such:
```
:root {
  --main-bg-color: blue;
}
```
However, cssutils errors with the following error message when attempting to use this:
`xml.dom.SyntaxErr: CSSStyleDeclaration: Unexpected token, ignoring upto '--main-bg-color: blue;'`

For larger projects, custom variables are a necessecity, especially when not utilizing SCSS or SASS.

**Comment by Glamurio** [comment]
Upon further inspection, I noticed that the actual underlying issue seems to be that it errors out when prepending the property name with '--', unfortunately that's a requirement for custom variables. I'm struggling to find the exact spot where the error is being produced in an effort to, at the very least, provide a patch for this issue.

**Comment by vinicvaz** [comment]
following

**Comment by jaraco** [comment]
Just chiming in to say that I don't have much experience with this package, but as the maintainer, I welcome you to continue to work on it and develop a solution.
