### ISSUE TITLE
RFE: Replace use of `pkg_resources` with `importlib.metadata`

### ISSUE THREAD

**Issue by kloczek** [jaraco/cssutils#22]
See discussions:
[astropy/astropy#11091](https://github.com/astropy/astropy/pull/11091)
[pypa/pip#7413](https://github.com/pypa/pip/issues/7413)

```console
[tkloczko@devel-g2v SRPMS]$ rpm -ql python-cssutils | grep py$ | xargs grep pkg_resources
/usr/lib/python3.8/site-packages/cssutils/tests/basetest.py:        from pkg_resources import resource_filename
```

**Comment by kloczek** [comment]
Q about about cssutils/tests/
IS that directory is not by mistake installed? Looks like it is test suite and probably whole install exclude list 🤔

**Comment by jaraco** [comment]
I’m not too bothered if tests are installed. If you would like to file a feature request, this project could consider it.

**Comment by kloczek** [comment]
If those files are only private test suite ad have no any other use case those files should be not installed.

So Q is: do you know anything that cssutils/tests/ is currently used by any other modules? If answer is "no" than those files should not be installed.
