### ISSUE TITLE
Dependency on lxml breaks CI on Python 3.11

### ISSUE THREAD

**Issue by jaraco** [jaraco/cssutils#25]
Once again, I'm finding the lxml dependency means the CI pipelines are broken in Python 3.11 until lxml provides binary builds for that Python version.

_Originally posted by @jaraco in https://github.com/jaraco/cssutils/issues/24#issuecomment-1150273294_

**Comment by jaraco** [comment]
Last year, it took ~3 months to get wheels (https://bugs.launchpad.net/lxml/+bug/1929359).

**Comment by jaraco** [comment]
Filed https://bugs.launchpad.net/lxml/+bug/1977998 to track the need for Python 3.11.

**Comment by jaraco** [comment]
Workaround is sufficient for now.

**Comment by jayaddison** [comment]
A note that I _think_ this might be re-resolvable (for most platforms) by unpinning the `lxml` dependency in `setup.cfg`.

One catch to look out for, though: some versions of MacOS appear to have trouble building `lxml` from source (which they attempt by default during installation of that package) -- but are generally fine when using prebuilt binary wheels.
