### ISSUE TITLE
How compatible to 1.0 is the 2.4 version?

### ISSUE THREAD

**Issue by adrien-n** [jaraco/cssutils#31]
Hi,

Debian and Ubuntu have been shipping 1.0 for the past ~5 years and now there's a new build failure with it. Unsurprisingly, it looks fixed in the versions here.

Considering how many years separate these two versions, I'd like to know how compatible these two versions are. I also tried reaching @cthedot by e-mail but that bounced.

Thanks. :)

**Comment by stefan6419846** [comment]
Did you have a look at the changelog? https://github.com/jaraco/cssutils/blob/main/CHANGES.rst Skimming through it, there mostly seem to have happened internal refactorings and at least Python 3.7 is required now.

**Comment by jaraco** [comment]
Thanks Stefan. The [changelog is also available in the docs](https://cssutils.readthedocs.io/en/latest/history.html) and there the changes are annotated with dates and links to issues.

I would expect this version to be completely compatible, given that the only backward-incompatible release was 2.0 and that bump was for the dropping of support for older Pythons.

Let me know if you find that's not the case.
