### ISSUE TITLE
cgi deprecation warning

### ISSUE THREAD

**Issue by gumaerc** [jaraco/cssutils#49]
In 2.10.2 (the latest version) I'm seeing a deprecation warning:

```python
/opt/venv/lib/python3.12/site-packages/cssutils/_fetchgae.py:6: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  import cgi
```

It seems this is still being using in this `_fetchgae.py` file, which has something to do with Google AppEngine? Can we remove this reference or update it? I saw https://github.com/jaraco/cssutils/commit/9d69993c581e2b3c2332524998136c88f122e96c which removed other references to `cgi` but one still remains.

**Comment by jaraco** [comment]
Done in 3b3e498d6009e076b7cf990102f649c86f6080ec.
