### ISSUE TITLE
License Confusion

### ISSUE THREAD

**Issue by patrickplynch** [jaraco/cssutils#52]
Hello cssutils team,

I just want to make sure that this project is indeed licensed under the LGPL v3.0. As such, is there any reason to include the GPL license (via the /COPYING file) in the source code?

Thanks for your time!

**Comment by jaraco** [comment]
`cssutils` is dual-licensed, covered by both licenses. Therefore, yes, the project is indeed licensed under the LGPL v3.0.

> As such, is there any reason to include the GPL license (via the /COPYING file) in the source code?

Although I am not a lawyer, my understanding is that a user of the project may elect any suitable license for their use. That is, for this project, a user may use it under the GPL or the LGPL license. I don't know if that means the GPL is entirely subsumed by the LGPL.

Thought about another way, does the LGPL license grant the right to remove the GPL license? I think it does.

More importantly, when the license files were added by the original author (f106612510bc1c08a735a5e96612d0d18c87c5c5), their prose indicated "cssutils is published under the LGPL 2.1 or later", suggesting that the GPL license was superfluous from the start.

I'll remove the GPL license.

**Comment by jaraco** [comment]
Note that I force-pushed c77a435 over 21ab9c9 (which was a mistake).
